import {StyleSheet} from 'react-native';

/**
 * Styles for DefaultAddress — extracted to keep the component under 500 lines.
 */
export const styles = StyleSheet.create({
  scroll: {flex: 1, backgroundColor: '#fff'},
  container: {padding: 16, paddingBottom: 32},
  containerDesktop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 24,
    maxWidth: 1200,
    alignSelf: 'center',
    width: '100%',
  },
  formPane: {width: '100%'},
  formPaneDesktop: {flex: 1, maxWidth: 560},
  field: {marginBottom: 10, position: 'relative', zIndex: 1},
  fieldRaised: {zIndex: 30, elevation: 8},
  label: {fontSize: 13, fontWeight: '600', marginBottom: 4, color: '#334155'},
  input: {
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#fff',
  },
  select: {
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: '#F8FAFC',
  },
  dropdown: {
    maxHeight: 220,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 8,
    marginTop: 4,
    backgroundColor: '#fff',
    zIndex: 40,
    elevation: 8,
  },
  option: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  row: {flexDirection: 'row', alignItems: 'center'},
  flex: {flex: 1},
  half: {flex: 1},
  gap8: {gap: 8},
  loader: {marginLeft: 8},
  error: {color: '#B91C1C', marginBottom: 8},
  hint: {color: '#64748B', marginBottom: 8, fontSize: 12},
  mapPane: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    backgroundColor: '#F8FAFC',
    padding: 16,
    gap: 12,
  },
  mapPaneDesktop: {flex: 1, minHeight: 560},
  mapPaneTitle: {fontWeight: '700', fontSize: 15, color: '#0F172A'},
  mapImage: {
    width: '100%',
    height: 220,
    borderRadius: 10,
    backgroundColor: '#E2E8F0',
  },
  mapImageDesktop: {height: 360},
  liveMap: {
    width: '100%',
    height: 220,
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: '#E2E8F0',
  },
  liveMapDesktop: {height: 360},
  facadeImage: {
    width: '100%',
    height: 180,
    borderRadius: 10,
    backgroundColor: '#E2E8F0',
  },
  mapPlaceholder: {
    height: 220,
    borderRadius: 10,
    backgroundColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
  },
  facadePlaceholder: {
    minHeight: 120,
    borderRadius: 10,
    backgroundColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
  },
  mapPlaceholderTitle: {
    fontWeight: '700',
    color: '#334155',
    marginBottom: 6,
  },
  mapPlaceholderText: {
    color: '#64748B',
    textAlign: 'center',
    fontSize: 13,
    lineHeight: 18,
  },
  actions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
    marginTop: 16,
  },
  btnSecondary: {paddingHorizontal: 16, paddingVertical: 12},
  btnPrimary: {
    backgroundColor: '#2563EB',
    borderRadius: 8,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  btnPrimaryText: {color: '#fff', fontWeight: '600'},
  btnSecondaryText: {color: '#475569', fontWeight: '600'},
  btnDisabled: {opacity: 0.6},

  coordRow: {
    flexDirection: 'row',
    gap: 12,
  },
  coordField: {
    flex: 1,
  },
  inputReadonly: {
    backgroundColor: '#F1F5F9',
    color: '#475569',
  },
});