import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  toolbar: {padding: 12, gap: 8, borderBottomWidth: 1, flexShrink: 0},
  row: {flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 8},
  search: {flex: 1, maxWidth: 620, minWidth: 210, flexDirection: 'row', alignItems: 'center', gap: 8, borderWidth: 1, borderRadius: 8, paddingHorizontal: 10},
  searchMobile: {flexBasis: '100%', maxWidth: '100%', minWidth: 0},
  input: {flex: 1, minWidth: 0, height: 42, fontSize: 14},
  inputMobile: {fontSize: 16},
  button: {minHeight: 44, minWidth: 44, paddingHorizontal: 10, borderWidth: 1, borderRadius: 8, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6},
  label: {fontSize: 12, fontWeight: '600'},
  small: {fontSize: 12},
  chips: {flexDirection: 'row', flexWrap: 'wrap', gap: 6, alignItems: 'center'},
  chip: {minHeight: 30, maxWidth: '100%', borderWidth: 1, borderRadius: 18, paddingHorizontal: 9, flexDirection: 'row', alignItems: 'center', gap: 6},
  secondary: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 8},
  mode: {flexDirection: 'row', gap: 3},
  backdrop: {flex: 1, alignItems: 'center', justifyContent: 'center', padding: 16},
  sheet: {width: '100%', maxWidth: 480, maxHeight: '85%', borderWidth: 1, borderRadius: 14, padding: 16, gap: 12},
  sheetHeader: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10},
  sheetTitle: {fontSize: 17, fontWeight: '600'},
  option: {minHeight: 44, paddingVertical: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8},
  footer: {padding: 10, flexShrink: 0, borderTopWidth: 1, flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', gap: 8},
  pager: {flexDirection: 'row', flexWrap: 'wrap', gap: 4, alignItems: 'center'},
  page: {minWidth: 44, minHeight: 44, borderWidth: 1, borderRadius: 7, justifyContent: 'center', alignItems: 'center'},
  disabled: {opacity: 0.45},
  cardItem: {flexDirection: 'column', alignItems: 'stretch', borderWidth: 1, borderRadius: 12, overflow: 'hidden', margin: 0},
  cardActions: {alignSelf: 'stretch', flexDirection: 'row', justifyContent: 'flex-end', borderTopWidth: 1, paddingHorizontal: 12, paddingVertical: 8},
});
