import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  field: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#CBD5E1',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
    minHeight: 38,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  valueWrap: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    minWidth: 0,
  },
  valueText: {
    color: '#0F172A',
    flex: 1,
    fontSize: 13,
    fontWeight: '700',
    minWidth: 0,
  },
  placeholderText: {
    color: '#94A3B8',
  },
  modalOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.38)',
    flex: 1,
    justifyContent: 'center',
    padding: 18,
  },
  modalPanel: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    maxHeight: '82%',
    maxWidth: 280,
    padding: 14,
    width: '100%',
  },
  modalHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  modalTitle: {
    color: '#0F172A',
    fontSize: 16,
    fontWeight: '800',
  },
  closeButton: {
    alignItems: 'center',
    backgroundColor: '#F1F5F9',
    borderRadius: 8,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  searchInput: {
    backgroundColor: '#F8FAFC',
    borderColor: '#CBD5E1',
    borderRadius: 8,
    borderWidth: 1,
    color: '#0F172A',
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 10,
    minHeight: 38,
    paddingHorizontal: 10,
  },
  options: {
    gap: 6,
  },
  optionRow: {
    alignItems: 'center',
    borderColor: '#E2E8F0',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  optionRowActive: {
    backgroundColor: '#EFF6FF',
    borderColor: '#93C5FD',
  },
  optionGlyph: {
    alignItems: 'center',
    height: 24,
    justifyContent: 'center',
    width: 24,
  },
  optionText: {
    color: '#0F172A',
    flex: 1,
    fontSize: 13,
    fontWeight: '800',
    minWidth: 0,
  },
  optionTextActive: {
    color: '#1D4ED8',
  },
});
