import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  wrap: {
    width: '100%',
    minWidth: 0,
  },
  readButton: {
    minHeight: 28,
    width: '100%',
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  readValueWrap: {
    flex: 1,
    minWidth: 0,
    maxWidth: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  readBadge: {
    flex: 0,
    alignSelf: 'flex-start',
    minWidth: 22,
    minHeight: 22,
    maxWidth: '100%',
    borderWidth: 1,
    borderRadius: 6,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  readBadgeText: {
    flex: 0,
    flexShrink: 0,
    maxWidth: '100%',
    fontSize: 11,
    fontWeight: '800',
  },
  readTextBadge: {
    flex: 1,
    maxWidth: '100%',
  },
  readBadgeIcon: {
    flexShrink: 0,
  },
  readImage: {
    width: 16,
    height: 16,
    flexShrink: 0,
  },
  readButtonForm: {
    minHeight: 34,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 8,
    paddingHorizontal: 10,
    backgroundColor: '#FFFFFF',
  },
  readText: {
    flex: 1,
    minWidth: 0,
    color: '#0F172A',
    fontSize: 13,
    fontWeight: '600',
  },
  mutedText: {
    color: '#94A3B8',
  },
  editIcon: {
    flexShrink: 0,
  },
  fieldLabel: {
    marginBottom: 4,
    color: '#64748B',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  editingWrap: {
    width: '100%',
    minWidth: 0,
  },
  editingRow: {
    width: '100%',
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  input: {
    flex: 1,
    minWidth: 0,
    height: 32,
    borderWidth: 1,
    borderColor: '#93C5FD',
    borderRadius: 8,
    paddingHorizontal: 8,
    color: '#0F172A',
    fontSize: 13,
    fontWeight: '600',
    backgroundColor: '#FFFFFF',
  },
  formInput: {
    height: 34,
    borderColor: '#CBD5E1',
    paddingHorizontal: 10,
  },
  cancelButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CBD5E1',
  },
  savingText: {
    marginTop: 2,
    color: '#64748B',
    fontSize: 9,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  validationText: {
    marginTop: 3,
    color: '#DC2626',
    fontSize: 10,
    fontWeight: '800',
  },
});

export default styles;
